# version.properties
app.version=${project.version}
app.name=${project.name}
build.timestamp=${maven.build.timestamp}
git.commit=${git.commit.id.full}
git.branch=${git.branch}
project.url=${project.url}
copyright.start=${copyright.start}
copyright.holders=${project.organization.name}
